SET input_format_allow_errors_num = 1000;
SET input_format_allow_errors_ratio = 0.5;
SET format_csv_allow_single_quotes = 1;
SET format_csv_allow_double_quotes = 1;

INSERT INTO default.tmp_data
SELECT
    id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    parseDateTimeBestEffortUS(sale_date) as sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    parseDateTimeBestEffortUS(product_release_date) as product_release_date,
    parseDateTimeBestEffortUS(product_expiry_date) as product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM file(
        '/var/lib/clickhouse/user_files/MOCK_DATA6.csv',
        'CSV',
        'id UInt32, customer_first_name String, customer_last_name String, customer_age UInt8, customer_email String, customer_country String, customer_postal_code String, customer_pet_type String, customer_pet_name String, customer_pet_breed String, seller_first_name String, seller_last_name String, seller_email String, seller_country String, seller_postal_code String, product_name String, product_category String, product_price Decimal64(2), product_quantity UInt32, sale_date String, sale_customer_id UInt32, sale_seller_id UInt32, sale_product_id UInt32, sale_quantity UInt32, sale_total_price Decimal64(2), store_name String, store_location String, store_city String, store_state String, store_country String, store_phone String, store_email String, pet_category String, product_weight Decimal64(2), product_color String, product_size String, product_brand String, product_material String, product_description String, product_rating Decimal32(1), product_reviews UInt32, product_release_date String, product_expiry_date String, supplier_name String, supplier_contact String, supplier_email String, supplier_phone String, supplier_address String, supplier_city String, supplier_country String'
     );

INSERT INTO default.tmp_data
SELECT
    id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    parseDateTimeBestEffortUS(sale_date) as sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    parseDateTimeBestEffortUS(product_release_date) as product_release_date,
    parseDateTimeBestEffortUS(product_expiry_date) as product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM file(
        '/var/lib/clickhouse/user_files/MOCK_DATA7.csv',
        'CSV',
        'id UInt32, customer_first_name String, customer_last_name String, customer_age UInt8, customer_email String, customer_country String, customer_postal_code String, customer_pet_type String, customer_pet_name String, customer_pet_breed String, seller_first_name String, seller_last_name String, seller_email String, seller_country String, seller_postal_code String, product_name String, product_category String, product_price Decimal64(2), product_quantity UInt32, sale_date String, sale_customer_id UInt32, sale_seller_id UInt32, sale_product_id UInt32, sale_quantity UInt32, sale_total_price Decimal64(2), store_name String, store_location String, store_city String, store_state String, store_country String, store_phone String, store_email String, pet_category String, product_weight Decimal64(2), product_color String, product_size String, product_brand String, product_material String, product_description String, product_rating Decimal32(1), product_reviews UInt32, product_release_date String, product_expiry_date String, supplier_name String, supplier_contact String, supplier_email String, supplier_phone String, supplier_address String, supplier_city String, supplier_country String'
     );

INSERT INTO default.tmp_data
SELECT
    id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    parseDateTimeBestEffortUS(sale_date) as sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    parseDateTimeBestEffortUS(product_release_date) as product_release_date,
    parseDateTimeBestEffortUS(product_expiry_date) as product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM file(
        '/var/lib/clickhouse/user_files/MOCK_DATA8.csv',
        'CSV',
        'id UInt32, customer_first_name String, customer_last_name String, customer_age UInt8, customer_email String, customer_country String, customer_postal_code String, customer_pet_type String, customer_pet_name String, customer_pet_breed String, seller_first_name String, seller_last_name String, seller_email String, seller_country String, seller_postal_code String, product_name String, product_category String, product_price Decimal64(2), product_quantity UInt32, sale_date String, sale_customer_id UInt32, sale_seller_id UInt32, sale_product_id UInt32, sale_quantity UInt32, sale_total_price Decimal64(2), store_name String, store_location String, store_city String, store_state String, store_country String, store_phone String, store_email String, pet_category String, product_weight Decimal64(2), product_color String, product_size String, product_brand String, product_material String, product_description String, product_rating Decimal32(1), product_reviews UInt32, product_release_date String, product_expiry_date String, supplier_name String, supplier_contact String, supplier_email String, supplier_phone String, supplier_address String, supplier_city String, supplier_country String'
     );

INSERT INTO default.tmp_data
SELECT
    id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    parseDateTimeBestEffortUS(sale_date) as sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    parseDateTimeBestEffortUS(product_release_date) as product_release_date,
    parseDateTimeBestEffortUS(product_expiry_date) as product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM file(
        '/var/lib/clickhouse/user_files/MOCK_DATA9.csv',
        'CSV',
        'id UInt32, customer_first_name String, customer_last_name String, customer_age UInt8, customer_email String, customer_country String, customer_postal_code String, customer_pet_type String, customer_pet_name String, customer_pet_breed String, seller_first_name String, seller_last_name String, seller_email String, seller_country String, seller_postal_code String, product_name String, product_category String, product_price Decimal64(2), product_quantity UInt32, sale_date String, sale_customer_id UInt32, sale_seller_id UInt32, sale_product_id UInt32, sale_quantity UInt32, sale_total_price Decimal64(2), store_name String, store_location String, store_city String, store_state String, store_country String, store_phone String, store_email String, pet_category String, product_weight Decimal64(2), product_color String, product_size String, product_brand String, product_material String, product_description String, product_rating Decimal32(1), product_reviews UInt32, product_release_date String, product_expiry_date String, supplier_name String, supplier_contact String, supplier_email String, supplier_phone String, supplier_address String, supplier_city String, supplier_country String'
     );

INSERT INTO default.tmp_data
SELECT
    id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    parseDateTimeBestEffortUS(sale_date) as sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    parseDateTimeBestEffortUS(product_release_date) as product_release_date,
    parseDateTimeBestEffortUS(product_expiry_date) as product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM file(
        '/var/lib/clickhouse/user_files/MOCK_DATA.csv',
        'CSV',
        'id UInt32, customer_first_name String, customer_last_name String, customer_age UInt8, customer_email String, customer_country String, customer_postal_code String, customer_pet_type String, customer_pet_name String, customer_pet_breed String, seller_first_name String, seller_last_name String, seller_email String, seller_country String, seller_postal_code String, product_name String, product_category String, product_price Decimal64(2), product_quantity UInt32, sale_date String, sale_customer_id UInt32, sale_seller_id UInt32, sale_product_id UInt32, sale_quantity UInt32, sale_total_price Decimal64(2), store_name String, store_location String, store_city String, store_state String, store_country String, store_phone String, store_email String, pet_category String, product_weight Decimal64(2), product_color String, product_size String, product_brand String, product_material String, product_description String, product_rating Decimal32(1), product_reviews UInt32, product_release_date String, product_expiry_date String, supplier_name String, supplier_contact String, supplier_email String, supplier_phone String, supplier_address String, supplier_city String, supplier_country String'
     );

INSERT INTO default.main_data
SELECT
    rowNumberInAllBlocks() as id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    parseDateTimeBestEffortUS(sale_date) as sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    parseDateTimeBestEffortUS(product_release_date) as product_release_date,
    parseDateTimeBestEffortUS(product_expiry_date) as product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM default.tmp_data;

DROP TABLE default.tmp_data;